### ISSUE TITLE
Can't see word count?

### ISSUE THREAD

**Issue by jkaczmarski** [pengx17/logseq-plugin-random-tools#1]
Hi. I love the idea of having word count in logseq, so thanks for making this plugin. However, even after installing and enabling this plug-in in logseq, i can not see the word count.. any ideas why this may be? Currently running Logseq Version 0.3.9 (0.3.9) on MacOS 11.3

**Comment by pengx17** [comment]
Hi, how did you install this plugin? You need to download it via [the release page](https://github.com/pengx17/logseq-plugin-random-tools/releases).

**Comment by jkaczmarski** [comment]
Thanks for the reply. I have just uninstalled and reinstalled (a freshly downloaded) this, and it is working now! I installed it the same way the first time (and same version), so not sure why it was not working! Thanks

**Comment by pengx17** [comment]
I think some functions will only be enabled once you reload the App? I am not sure about that 😅
