### ISSUE TITLE
When is the plugin marketplace for logseq going live?

### ISSUE THREAD

**Issue by wenshangshang** [pengx17/logseq-plugin-random-tools#2]
Great plugin, counting document words is a very much needed feature for me. When will I be able to access and download him from the plugin marketplace please?

**Comment by pengx17** [comment]
Not too soon. Word count requires a way to hack into the main view, which is banned to plugin installed via market place.

**Comment by RedemptionC** [comment]
@pengx17 Hi,is this plugin on the marketplace? what's the name ?

**Comment by pengx17** [comment]
I think there is another one that serves a similar purpose https://github.com/hkgnp/logseq-wordcount-plugin
The current implementation of the random-tools uses a deprecated logseq API and I do not feel like adapting for the latest version. Sorry about that
